---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Box Sync/Personal Website/templates/svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Julie M Mallon

jobtitle: "Movement Ecologist, PhD Candidate"
address: "Biological Sciences · University of Maryland · College Park, MD 20012 · USA"
fontawesome: yes
email: jmmallon@umd.edu
web: terpconnect.umd.edu/~jmmallon/
updated: no

#keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#from https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-rmarkdown-cv.Rmd
```


#EDUCATION
*University of Maryland, College Park, Maryland* | PhD program, Biological Sciences \hfill 2015 – present 

*West Virginia University, Morgantown, West Virginia* | M.Sc., Wildlife Management  \hfill 2015  

*Universidad San Francisco de Quito, Quito, Ecuador* | Tropical Ecology Program \hfill 2011  

*Boston University, Boston, Massachusetts* | B.A., Biology (Ecology and Conservation Biology) \hfill 2012   


#RESEARCH
##University of Maryland 
- Environmental drivers of stopover use by Turkey Vultures (*Cathartes aura*)
- Energetic costs of migration and stopover use by Turkey Vultures (*Cathartes aura*)
- Phylogenetic and ecological signals in avian movements 


##West Virginia University			  
- Turbulent uplift use by Cathartid vultures
- Global-scale response to uplift availability by soaring black and turkey vultures  


#PUBLICATIONS
Mallon, J. M., K. L. Bildstein, and T. E. Katzner. 2016. In-flight turbulence benefits soaring birds. The Auk, 133: 79-85. 

Mallon, Julie M., Kelly Swing, and Diego Mosquera. 2013. Neotropical vulture scavenging succession at a capybara carcass in eastern Ecuador. Ornitología Neotropical, 24: 475-480. 

Mallon, J., K. Rittenhouse, C. Turrin, W. Frew, and K.L. Bildstein. 2011. Kestrels of the world. Hawk Mountain Sanctuary Association. Published online.

#GRANTS AND AWARDS
Graduate School Summer Fellowship | University of Maryland, College Park \hfill 2017  
Department of Biology Travel Award | University of Maryland, College Park \hfill 2016  
Mentor Honorarium | California State University, Monterey Bay  \hfill 2016  
Dean's Summer Fellowship | University of Maryland, College Park \hfill 2015  
Project Soar Award | Hawk Mountain Sanctuary, Kempton, PA \hfill 2013		


#PRESENTATIONS  
Raptor Research Foundation | Salt Lake City, UT \hfill 2017  
North American Ornithological Society | Washington, DC \hfill 2016  
Wilson Ornithological Society and Association of Field Ornithologists | Providence, RI \hfill 2014  
Monticello Bird Club | Charlottesville, Virginia		\hfill  2014	  
Mountaineer Audubon | Morgantown, West Virginia \hfill 2013  

#PROGRAMMING OUTREACH PROJECTS
R shiny web application to automate exploration and analysis of movement data  
Published dissertation and manuscript template using Markdown  
Personal website built and maintained with Markdown to host course materials for students   

	 
#SKILLS
Programs and Languages:  GrADs, ArcMap, R software, Python, UNIX, HTML, Markdown  
Conservation Leaders for Tomorrow (CLfT) – hunter safety course \hfill 2013  

#TEACHING
##University of Maryland
- Ecology, Evolution, and Biodiversity \hfill 2015 - 2018  
- Guest lectured for R statistical course \hfill 2018
- Anatomy and Physiology Lab  \hfill 2016  

#FIELD EXPERIENCE
##Max Planck Institute, Seewiesen, Germany  
-	Surveyed nest boxes  \hfill 2012
-	Conducted transects and aggression tests
-	Trapped, bled, banded nestlings and adult passerines

##Tiputini Biodiversity Station, Ecuador  
-	Mistnetted bats \hfill 2011 
-	Measured and identified 34 species of neotropical bats

##Hawk Mountain Acopian Center, Kempton, PA 
-	Observed behavior of fledgling American Kestrels in the field using color bands \hfill 2011 
-	Developed education materials for children about raptor conservation
-	Worked on the ongoing American Kestrel nestbox program by measuring and banding kestrel nestlings
-	Assisted in tagging, bleeding, and measuring of adult and juvenile turkey and black vultures


    

