---
title: "Critical Thinking"
author: "Julie Mallon"
date: "August 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

----

#Thinking Critically

## Be a skeptic

Logical necessities:
- Falsifiability
- Logic
- Comprehensiveness

Prgamatic necessities
- Honesty
- Replicability
- Sufficientcy

## Falsifiability
It must be possible to conceive of evidence that would prove the claim false. 
  - any evidence can either 'support' or *falisfy* a claim 

Any claim that cannot be falsified is a belief/emotive statement
  - no evidence will support or falsify the claim
    - e.g. all Nic Cage movies are terrible
    > * How do you quantify terrible? *
    
  - either too broad or vague to be defined
    - e.g. climate change is a conspiracy
    
  - or evidence does falsify the claim
      - use other nonfalsifiable claims to reject evidence
      - e.g. pictures of the earth that depict it as a sphere are photoshopped 
      
## Logic
Any argument offered as evidence in support of any claim must be sound
- valid if conclusion follows unavoidably from its premises
- sound if it's premises are true

Invalid if you can think of a counter-example or not all premises are true
1. All dogs have fur; Mittens has fur; therefore, Mittens is a dog
2. All dogs have fur -> my dog, therefore, has fur

## Comprehensiveness 
All of the available evidence must be considered
- E.g. rejecting the evidence of climate change

## Honesty
The evidence offered in support of any claim must be evaluated without self-deception

## Replicability
Due to error, fraud, chance, and coincidence, experiments must be repeated to support a claim as true

## Sufficiency
The evidence offered must be adequate to estabilish the truth of the claim

---

## Applying this to science in the media | Possible questions to ask yourself


- Falsifiability
    - Does their evidence support their hypothesis?
    - Can you think of evidence that would reject their hypothesis?
- Logic
    - Are their arguments valid and sound, or flawed?
    - Does their experiment even *test* their hypothesis?
- Comprehensiveness
    - Do they ignore any available evidence?
- Honesty
    - Is the study biased? 
    - Do the raw results agree with their statements in the discussion and abstract?
    - Are their statistical analyses correct?
- Replicability
    - Could this study be reproduced? Do they describe their methods in sufficient detail?
- Sufficientcy
    - What is their sample size? 
    - What organism/population are they testing? 


## Andrew Wakefield - The Anti-vax movement
If you have heard of the anti-vaccine controversy, the primary support for this movement comes from a 1998 paper by Wakefield et al. which was later **retracted** by the journal. Here is a brief overview of the science behind the controversy.

> Wakefield had a study of 12 children with gastrointestinal problems, looking for a link with the MMR vaccine. <br>
> Wakefield 'selected' some of these children to use in a separate study looking at the link of MMR and autism, and were contacted by concerned parents of children with autism that had heard about his study. He was paid by "soliciters seeking evidence against the manufacturers" (Deer 2004). Methods for this 1998 were qualitative, not quantitiative.<br>
> The first article made no claims about the connect of MMR vaccination and autism or Crohn's disease. During a press conference, Wakefield stated that parents should opt out of the MMR vaccine and get the 3 separate vaccinations instead.

sources: 1, 2, 3, 4

##What are the problems with the study?
- sample size of 12
- subjects were not randomly selected - they were selected because they were consistent with his hypothesis
- Wakefield was paid by a source that was looking for damaging evidence against the manufacturers of a vaccine; this is a 'conflict of interest'
- Methods are not replicable as qualitiative data are inconsistent
- Wakefield's claim is not supported by any evidence
- Wakefield's claim not falsifiable

## Recent Health Science Publication
[Vitamin B3 could prevent birth defects, miscarriages, scientists say](www.foxnews.com/health/2017/08/10/vitamin-b3-could-prevent-birth-defects-miscarriages-scientists-say.html)
By Katherine Lam (Published August 10, 2017 Fox News)


Article text is reprinted below for educational purposes. Statements are highlighted that are <span style="color: blue">true</span>, <span style="color: red">false</span>, or represent an <span style="color: green">opinon</span>. I've added [comments] to clarify some annotations.

<!-- CSS -->
<style>
/* Force scrollbars onto browser window */
body {
margin-bottom: 200%;
}

/* Box styles */
.myBox {
border: none;
padding: 5px;
font: 14px/18px sans-serif;
width: 700px;
height: 400px;
overflow: scroll;
}
</style>


<!-- HTML -->
<div class="myBox">

<span style="color: red">Marmite, which contains loads of vitamin B3, could help prevent birth defects and miscarriages,</span> a new study revealed.
 (Reuters) [While Marmite contains B3, the study did not test if marmite prevents birth defects or miscarriages *of baby mice*]

<span style="color: green">
Women who are pregnant, or thinking about have children soon, may want to start stocking up on marmite.
</span>
<span style="color: red">
Scientists in Australia revealed in a new study pregnant women could prevent birth defects and miscarriages if they get an extra dose of the dietary supplement vitamin B3.
</span>
Researchers from the Victor Change Institute in Sydney, Australia, said <span style="color: green">their "double breakthrough" findings</span> <span style="color: blue">identified nicotinamide adenine dinucleotide (NAD) as the vital nutrient that keeps babies in wombs healthy during pregnancy. </span> [*assuming Dunwoodie meant baby mice*]


<span style="color: green">
"Now, after 12 years of research, our team has also discovered that this deficiency can be cured and miscarriages and birth defects prevented by taking a common vitamin,"</span>  Professor Dunwoodie, who lead the study, said in a statement. 

<span style="color: blue">
Lab tests involving pregnant mice showed that placing vitamin B3, also known as niacin, in their diets "completely prevented" miscarriages and defects and led to "perfectly healthy" babies being born. The dietary supplement, typically found in meats, green vegetables and marmite, helps create NAD. The organic compount is essential for DNA repair, cell communication and energy production, the report said. </span>

<span style="color: blue">
About 60 percent of pregnant woman in their third trimester were found to have low levels of vitamin B3, according to the report. </span>[*true, but irrelevant!*] 
<span style="color: blue">
Every year, 7.9 million newborns worldwide suffer from a birth defect. One in four women also suffer from a miscarriage.
</span> 
[*true, but irrelevant!*]

<span style="color: green">
Researchers said the next steps are to find a way to measure NAD levels in pregnant woman to identify who needs more vitamin B3. <br><br> "We believe that this breakthrough will be one of our country’s greatest medical discoveries. It’s extremely rare to discover the problem and provide a preventive solution at the same time. It’s actually a double breakthrough,"</span> Professor Robert Graham, executive director of the Victor Chang Cardiac Research Institute, said.
</div>

</body>
</html>

<br>
The original statement from the Victor Chang Cardiac Research Institute is available [here](https://www.victorchang.edu.au/pregnancy-breakthrough).
Their original statement was a bit sensational, and on August 11, 2017 they [published a second statement to clarify the facts and implications of the study](https://www.victorchang.edu.au/pregnancy-breakthrough-statement).

*Disclaimer: This is in no way a criticism of the study's findings or merits, and is only to be used as a critical thinking and close reading exercise for students.*


## References
From: Lett, James. 1990. A Field Guide to Critical Thinking. Skeptical Inquirer, 14.2. url: <http://www.csicop.org/si/show/field_guide_to_critical_thinking>.  Accessed 11 August 2017.

Deer, Brian (22 February 2004). "Revealed: MMR research scandal". The Sunday Times. London. url: <https://www.thetimes.co.uk/article/revealed-mmr-research-scandal-7ncfntn8mjq> Accessed 11 August 2017.

"Profile: Dr Andrew Wakefield". BBC. 27 January 2010. Accessed 11 August 2017.
<http://news.bbc.co.uk/1/hi/3513365.stm>
